'use client';

import { useAppContext } from '@/context/AppContext';

interface OfferResultsProps {
  showToast: (
    type: 'success' | 'error' | 'warning' | 'info',
    title: string,
    message: string
  ) => void;
}

export const OfferResults = ({ showToast }: OfferResultsProps) => {
  const { state, saveOffer, setCurrentOffer } = useAppContext();

  if (!state.currentOffer) return null;
  const offer = state.currentOffer;

  const handleSaveOffer = () => {
    if (state.currentOffer) {
      saveOffer(state.currentOffer);
      showToast('success', 'Offer Saved', 'Your offer was saved successfully!');
    }
  };

  const handleGenerateNew = () => {
    setCurrentOffer(null);
  };

  const handleDownloadOffer = () => {
    if (!state.currentOffer) return;

    const offerData = state.currentOffer;

    const offerSheet = `
PROFESSIONAL REAL ESTATE OFFER SHEET
Generated by Offer AI Bot

PROPERTY INFORMATION
==========================================
Property Address: ${offerData.address}
Offer Type: ${offerData.offerType === 'cash' ? 'Cash Offer' : 'Creative Offer'}
Generated on: ${new Date().toLocaleDateString()}

FINANCIAL BREAKDOWN
==========================================
ARV (After Repair Value): $${offerData.arv.toLocaleString()}
Estimated Repairs: $${offerData.repairs.toLocaleString()}
ARV Percentage Used: ${offerData.arvPctUsed}%

COST ANALYSIS
==========================================
Holding Costs (${offerData.holdingPctUsed}%): $${offerData.holdingCosts.toLocaleString()}
Closing Costs (${offerData.closingPctUsed}%): $${offerData.closingCosts.toLocaleString()}
Total Additional Costs: $${(offerData.holdingCosts + offerData.closingCosts).toLocaleString()}

FINAL OFFER CALCULATION
==========================================
Base Amount (${offerData.arvPctUsed}% of ARV): $${Math.round(
      offerData.arv * (offerData.arvPctUsed / 100)
    ).toLocaleString()}
Less: Repairs: -$${offerData.repairs.toLocaleString()}
Less: Holding Costs: -$${offerData.holdingCosts.toLocaleString()}
Less: Closing Costs: -$${offerData.closingCosts.toLocaleString()}

FINAL OFFER: $${offerData.offerAmount.toLocaleString()}

ADDITIONAL NOTES
==========================================
${offerData.notes || 'No additional notes provided.'}

This offer was generated using professional real estate investment calculations and market analysis.
    `.trim();

    const blob = new Blob([offerSheet], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `offer-${offerData.address.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    showToast('success', 'Offer Downloaded', 'The offer has been downloaded!');
  };

  const handleShareOffer = () => {
    if (!state.currentOffer) return;

    const offerData = state.currentOffer;
    const shareText = `🏠 Professional Real Estate Offer Generated!\n\nProperty: ${
      offerData.address
    }\nOffer Amount: $${offerData.offerAmount.toLocaleString()}\nOffer Type: ${
      offerData.offerType === 'cash' ? 'Cash' : 'Creative'
    }\n\nGenerated by Offer AI Bot - Advanced Real Estate Investment Calculator`;

    if (navigator.share) {
      navigator.share({
        title: 'Real Estate Investment Offer',
        text: shareText,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(shareText).then(() => {
        showToast('info', 'Offer Copied', 'Offer details copied to clipboard!');
      });
    }
  };

  return (
    <div className="content-container">
      <div id="offer-results" className="offer-results-section">
        <div className="offer-results-content">
          {/* Title with target icon */}
          <h2 className="offer-results-title">
            <span className="target-icon">🎯</span>
            Your Recommended Offer
          </h2>

          {/* Large offer amount */}
          <div className="offer-amount">${offer.offerAmount.toLocaleString()}</div>

          {/* Offer type display */}
          <div className="offer-type-display">
            <span className="offer-type-icon">
              {offer.offerType === 'cash' ? '💵' : '🎨'}
            </span>
            {offer.offerType === 'cash' ? 'Cash Offer' : 'Creative Offer'}
          </div>

          {/* Breakdown section */}
          <div className="offer-breakdown">
            <h3 className="breakdown-title">Detailed Calculation Breakdown</h3>

            <div className="breakdown-row">
              <div className="breakdown-item">
                <span className="breakdown-label">Property ARV:</span>
                <span className="breakdown-value">${offer.arv.toLocaleString()}</span>
              </div>
              <div className="breakdown-item">
                <span className="breakdown-label">Holding Costs:</span>
                <span className="breakdown-value">${offer.holdingCosts.toLocaleString()}</span>
              </div>
            </div>

            <div className="breakdown-row">
              <div className="breakdown-item">
                <span className="breakdown-label">Repair Costs:</span>
                <span className="breakdown-value">${offer.repairs.toLocaleString()}</span>
              </div>
              <div className="breakdown-item">
                <span className="breakdown-label">Closing Costs:</span>
                <span className="breakdown-value">${offer.closingCosts.toLocaleString()}</span>
              </div>
            </div>

            <div className="breakdown-row">
              <div className="breakdown-item">
                <span className="breakdown-label">ARV Percentage:</span>
                <span className="breakdown-value">{offer.arvPctUsed}%</span>
              </div>
              <div></div>
            </div>

            <div className="final-offer-section">
              <div className="final-offer-item">
                <span className="final-offer-label">Final Offer:</span>
                <span className="final-offer-value">
                  ${offer.offerAmount.toLocaleString()}
                </span>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="offer-actions">
            <button className="action-btn save" onClick={handleSaveOffer} type="button">
              <span className="btn-icon">💾</span>
              Save Offer
            </button>
            <button className="action-btn generate" onClick={handleGenerateNew} type="button">
              <span className="btn-icon">🔄</span>
              Generate New
            </button>
            <button
              className="action-btn download hidden"
              onClick={handleDownloadOffer}
              type="button"
            >
              <span className="btn-icon">📥</span>
              Download PDF
            </button>
            <button
              className="action-btn share hidden"
              onClick={handleShareOffer}
              type="button"
            >
              <span className="btn-icon">🔗</span>
              Share Offer
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
